HAI
I HAS A DELAY ITZ 1000

HOW DUZ I SALUTE YR DUZ WAYT AN YR YOU
	VISIBLE "WAIT A SEC..."
	setTimeout WIZ WAYT AN DELAY ENUF
	VISIBLE "MOAR WAIT..."
	setTimeout WIZ WAYT AN DELAY ENUF
	VISIBLE SMOOSH "HELLO " AN YOU
IF U SAY SO

SALUTE WIZ WAYT AN " DUDE" ENUF
KTHXBYE
