I HAS A DELAY ITZ 1000

HOW DUZ I SALUTE YR WAIT FOR IT AN YR YOU
	VISIBLE "WAIT A SEC..."
	setTimeout WAIT FOR IT AN DELAY
	VISIBLE "MOAR WAIT..."
	setTimeout WAIT FOR IT AN DELAY
	VISIBLE SMOOSH "HELLO " AN YOU
IF U SAY SO

SALUTE DUDE WAIT WHAT? AN " DUDE"
KTHXBYE